### ISSUE TITLE
PropertyGrid Example: fails on selection of any sample

### ISSUE THREAD

**Issue by Hinidu** [objorke/PropertyTools#46]
Hello!
If I select anything in the left pane or click on any menu item in "PropertyGrid" menu then app fails with `NullReferenceException` in `MS.Internal.AvTrace.AntiFormat(string s)`.
StackTrace:

```
   at MS.Internal.AvTrace.AntiFormat(String s)
   at MS.Internal.AvTraceBuilder.AppendFormat(String message, String arg1, String arg2)
   at MS.Internal.TraceData.DescribeSourceObject(AvTraceBuilder traceBuilder, Object o)
   at MS.Internal.TraceData.DescribeTarget(AvTraceBuilder traceBuilder, DependencyObject targetElement, DependencyProperty targetProperty)
   at MS.Internal.TraceData.Describe(AvTraceBuilder traceBuilder, Object o)
   at MS.Internal.TraceData.OnTrace(AvTraceBuilder traceBuilder, Object[] parameters, Int32 start)
   at MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
   at MS.Internal.TraceData.Trace(TraceEventType type, AvTraceDetails traceDetails, Object p1)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at PropertyGridDemo.App.Main() in c:\Users\pavel.platto\Desktop\PropertyTools-master\Source\Examples\PropertyGrid\PropertyGridDemo\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by objorke** [comment]
Can this be reproduced in the examples? Need more info to reproduce!

**Comment by Hinidu** [comment]
Sorry, I wasn't explicit enough. As I stated in the issue title I encounter this issue exactly in PropertyGrid example.

**Comment by Hinidu** [comment]
> What do you mean by menu in the PropertyGrid?

Provided example app has menu named "PropertyGrid".

**Comment by objorke** [comment]
OK, but I cannot reproduce this error. All functions on the "PropertyGrid" menu works on this machine.

**Comment by Hinidu** [comment]
I open PropertyTools_Net45.sln in Visual Studio 2012 on Windows 8.1. Is your environment significantly different?

**Comment by objorke** [comment]
I see it works on Windows 7 but not on Windows 8.1. Thanks for reporting!

**Comment by hasol81** [comment]
I think that this issue was occured after revision no. 377.
r376 is still working normally.

**Comment by objorke** [comment]
Can't reproduce this. Please reopen if the problem persists.
